diffutils: upgrade to 3.6
diffutils-3.5-gcc7.patch is removed as it's merged in this version.

do_configure_prepend is removed to solve the following configure error.

  error: possibly undefined macro: gl_TYPE_WINT_T_PREREQ

A workaround patch is made to fix the following compilation error for glibc.

  error: dereferencing pointer to incomplete type 'const struct rpl_option'

(From OE-Core rev: 0c09f9f5700696670b2a9d0466124309100eb296)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>