acl: fix race issue when do_compile
Fixed race issue:
 In file included from acl_copy_entry.c:22:0:
 libacl.h:19:21: fatal error: sys/acl.h: No such file or directory
  #include <sys/acl.h>

[snip]

 compilation terminated.
 acl_get_file.c:27:24: fatal error: acl/libacl.h: No such file or directory
  #include <acl/libacl.h>
                         ^

The acl.h is in "include" directory, and include/Makefile creates
symlink "sys" and "acl" poinst to current dirctory:
$ ls include/ -l
acl -> .
sys -> .

So if "libacl" target runs before "include", the error would happen
since no "acl" or "sys" directory.

Let libacl depend on include can fix the problem.

[YOCTO #11349]

(From OE-Core rev: 73d3d81fcdb92dd85c6ad1609e3a6eb20f1ea539)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>