gpgme: Define __error_t_defined on musl
Configure looks for error_t in errno.h and musl does not define error_t
if its not defined then configure emits a definition to be used, now we
also use standalone argp implementation from glibc on musl based systems
which defines this in argp.h as well so now we have it defined twice
and errors like

|
/a/builder/mnt/build-oe/tmp-musl/sysroots/raspberrypi2/usr/include/argp.h:40:13:
error: cannot combine with previous 'int' declaration specifier
| typedef int error_t;
|             ^
| ../config.h:257:17: note: expanded from macro 'error_t'
| #define error_t int
|                 ^
| 1 error generated.

are seen. argp.h definition is conditional on __error_t_defined which is
true here so lets define it on musl

(From OE-Core rev: 29e1edcba39a21057ba5862eef4e79c177e7ef62)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>